name: rekord
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7 
  image_picker: ^0.8.7+4
  fl_chart: ^0.65.0
  video_player: ^2.8.2 
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/